### ISSUE TITLE
Invalid checksum for markup

### ISSUE THREAD

**Issue by stevenornelas** [codefoundries/isomorphic-material-relay-starter-kit#3] opened 2015-12-31 04:37 UTC
When I run locally in dev mode I get the following in the browser console:

```
React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server
```

When loading the initial page the screen visibly flashes as it redraws.

**Comment by thelordoftheboards** [comment] 2015-12-31 04:48
I am able to reproduce the issue. I found the following issue https://github.com/callemall/material-ui/issues/2336 on the Material-UI repository, I will look into implementing some of the ideas there.

**Comment by thelordoftheboards** [comment] 2015-12-31 05:11
I was able to implement the solution proposed by https://github.com/chadrien and it works well.

**Comment by bfwg** [comment] 2016-03-27 07:36
Hi, I have tried @thelordoftheboards solution and it is not working, my warning is:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <noscript data-reacti
 (server) <div data-reactid=".1
```
Is there a way to solve this?

Thanks

**Comment by thelordoftheboards** [comment] 2016-03-27 21:02
This has been an on and off problem. After some changes I was able to make it better, but not always.
Since React 15 will bring big changes to what will be in the actual DOM, namely the react id is going away, I figured out I would wait for it to come out, wait for whatever accompanying changes in Material-UI get released, and then look at it again. I will keep this open for now as a placeholder. If you figure it out in the meantime a PR would be greatly appreciated.

**Comment by thelordoftheboards** [comment] 2016-05-16 04:20
Will not be done for this project, use https://github.com/codefoundries/UniversalRelayBoilerplate instead.

**Closed by thelordoftheboards** 2016-05-16 04:20 UTC
Labels: Pending module update
